INSERT INTO decks(name,description) VALUES('Basic-JavaScript','Basic-JavaScript VOCAB DECK');
INSERT INTO decks(name,description) VALUES('HTML-CSS','HTML-CSS VOCAB DECK');
INSERT INTO decks(name,description) VALUES('CLI-Git-Github','CLI-Git-Github VOCAB DECK');
INSERT INTO decks(name,description) VALUES('DOM','DOM VOCAB DECK');
INSERT INTO decks(name,description) VALUES('DOM-Events','DOM-Events VOCAB DECK');
INSERT INTO decks(name,description) VALUES('DOM','DOM VOCAB DECK');
INSERT INTO decks(name,description) VALUES('JS-Event-Loop','JS-Event-Loop VOCAB DECK');
INSERT INTO decks(name,description) VALUES('AJAX-&-HTTP','AJAX-&-HTTP VOCAB DECK');
INSERT INTO decks(name,description) VALUES('Node-FS-HTTP-Express','Node-FS-HTTP-Express VOCAB DECK');
INSERT INTO decks(name,description) VALUES('ES6','ES6 VOCAB DECK');
INSERT INTO decks(name,description) VALUES('SQL-&-REST','SQL-&-REST VOCAB DECK');
INSERT INTO decks(name,description) VALUES('OOP-Part_1','OOP-Part_1 VOCAB DECK');
INSERT INTO decks(name,description) VALUES('OOP-Part_2 ','OOP-Part_2  VOCAB DECK');

INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a JavaScript Statement','Answer',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a Data Type in JavaScript','Answer',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a String in JavaScript','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a JavaScript Object','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Variable declaration','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Variable declaration','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a Function','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a Conditional Statement','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define the Accumulator Pattern','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Iterating','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Loops','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a Code Block','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Array Index','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Object Key','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Object Value','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Invoking a function','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Boolean','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Function arguments','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Function parameters','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Operators','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Comparison Operators','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Assignment Operators','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Logical Operators','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a return statement','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define console.log','ANSWER',1);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define Concatenation','ANSWER',1);


INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define HTML and what it can do','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define HTML Elements','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define  HTML Tags','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define HTML Attributes','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a Head Tag','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a Script Tag','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define a Body Tag','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define the "a" Tag','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define CSS and what it can do','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define CSS Rules','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define CSS Selectors','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define CSS Properties','ANSWER',2);
INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define CSS Values','ANSWER',2);

INSERT INTO flashcard(question,answer,deck_id) VALUES('Explain or define CSS Values','ANSWER',2);